### ISSUE TITLE
What does filterRange() do?

### ISSUE THREAD

**Issue by jehshPhilemon** [sciphp/numphp#2]
Hi,
I 'm trying to implant a RNN class in php originally written in python.
I've tried to implant some basic np.random class functions but I have A Problem when I Try use the library.
i don't know which method is causing this, here is exception message:

  Fatal error: Uncaught InvalidArgumentException: Expected a value between 0 and 0. Got: 1 in /home/htdocs/ai/numphp/webmozart/assert/src/Assert.php:2042 Stack trace:
#0 /home/htdocs/ai/numphp/webmozart/assert/src/Assert.php(922): Webmozart\Assert\Assert::reportInvalidArgument
('Expected a valu...') #1 /home/htdocs/ai/numphp/sciphp/numphp/src/SciPhp/NdArray/IndexTrait.php
(231): Webmozart\Assert\Assert::range(1, 0, 0) #2 /home/htdocs/ai/numphp/sciphp/numphp/src/SciPhp/NdArray/IndexTrait.php
(126): SciPhp\NdArray\Decorator->filterRange(Array, 0, 1) #3 /home/htdocs/ai/numphp/sciphp/numphp/src/SciPhp/NdArray/IndexTrait.php
(65): SciPhp\NdArray\Decorator->filterSet(Array, 0, Array, 1) #4 /
home/htdocs/ai/zeroml/rnn in
/home/htdocs/ai/numphp/webmozart/assert/src/Assert.php
on line 2042

I'm using these method np::argmax(), np::log(), np::exp(), np::sum(), np::tanh(), np::dot(), np::max()
and I Didn't find which among them throw this excption.
sorry for my bad english, I Speak frend

**Comment by landrok** [comment]
Hi, I speak french too so... Allons-y :)

La méthode `filterRange()` est une fonction interne qui sert à cibler des portions de matrices, elle est appelé par l'utilisation des index. Si besoin d'un peu de doc sur le sujet c'est ici https://sciphp.org/manual/en/ref.indexing.html.

Pour revenir sur l'implémentation, ça pourrait être top d'ajouter des fonctions random.

J'avais proposé quelques conseils à @bluescreen ici : https://github.com/sciphp/numphp/issues/1#issuecomment-510674310

L'exception qui est émise provient d'un range invalide. Le paramètre passé est 1 et le range de validation est [0, 0], la signature du validateur est `range($value, $min, $max)`.

Petit conseil pour me faciliter la lecture des traces, il vaut mieux les placer dans un bloc code.

Je ne peux pas en dire beaucoup plus sans un peu plus de détail. A priori et au doigt mouillé, je dirai que l'appel de l'index ne doit pas être valide. Est-ce que tu peux ajouter la trace complète et le morceau de code qui fait l'appel ?

Merci d'avance

**Comment by jehshPhilemon** [comment]
Merci, je vais voir la doc d'abord. Si je ne trouve pas ,je vais voir le code que je peux poster, c'est plus de 300 lignes.
puis il y a des methodes comme tanh(), cos(), np::random()... Qui peuvent être ajoutées .
Je suis en train d'ajouter celles que je vais utiliser, Merci.

**Comment by jehshPhilemon** [comment]
Merci pour Le conseil donné à @bluescreen #1 va trop aider pour l'ajout d'une class random, je verrai comment adapter le code de la class que j'ai écrit.
