### ISSUE TITLE
Docs website is down

### ISSUE THREAD

**Issue by georgemccann** [sciphp/numphp#3]
Can you fix the site, or upload the docs to git so they're still readable?

**Comment by landrok** [comment]
Hi georgemccann,

The website has just been migrated to a new server. The manual is ok, some icons are missing and the developper/api part is not yet available, it needs some work on the ci.

The docsare on github at [https://github.com/sciphp/numphp-doc](https://github.com/sciphp/numphp-doc).

Thanks for this issue.

**Comment by medecau** [comment]
This seems to have been solved.
Close?

**Comment by landrok** [comment]
Hi @medecau 

Icons have been "repaired" (CORS request), [API](https://sciphp.org/api/) has been migrated to Doctum.

This can now be considered as a solved problem ;)

Thanks
